spring.application.name=iflix

# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/iflix
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate - cria e atualiza as tabelas a partir das entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
